export const en = {
  'header.search': "Search",
  'footer.home': "Home",
  'footer.support': "Support",
  'footer.help': "Help",
  'main.attributes': "Atributele principale ale ansamblului rezidential",
  'secondary.attributes': "Atributele ansamblului rezidential",
  'save': "Salveaza",
  'delete': "Sterge",
  'edit': "Editeaza",
  'yes': "Da",
  'no': "Nu",
  'choose.license.steps': ["Alegerea temei", "Descrierea lucrarii", "Finalizare"],
  "upload.file": "Incarcare documentatie",
  "accepted.file.upload": ["application/msword", "application/pdf", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"],
  "student.license.fields": ["Titlu ", "Descriere ", "Documentatie ", "Tehnologii folosite "],
  "get.student.details.error": "Nu s-au putut primi datele despre student",
  "edit.student.details.error": "Nu s-au putut edita datele studentului",
  "edit.student.details.success": "S-au editat datele cu succes",
  "teachers.projects.error": "Nu s-au putut primi proiectele propuse de profesori",
  "teachers.error": "Nu s-a putut primi lista de profesori",
  "teacher.details.error": "Nu s-au putut primi datele despre profesor",
  "change.student.status.success": "S-a schimbat cu succes statusul studentului",
  "change.student.status.error": "Nu s-a putut schimba statusul studentului",
  "update.teacher.success": "S-au salvat cu succes modificarile",
  "update.teacher.error": "Nu s-a putut salva modificarile",
  "register.success": "Inregistare cu succes",
  "register.error": "Nu s-a putut efectua inregistrarea",
  "logout.success": "Delogare cu succes",
  "logout.error": "Nu s-a putut efectua delogarea",
};
